=== LongJohnCoder/RESim/cgc-monitor/zk/replayMaster/replay_master.dtd
<!ELEMENT replay_master (cache, clear_cache, workspace, cb_dir, cb_host, service_host?, local_replay?, ignore_header_errors?)>
<!ELEMENT cache (#PCDATA)>
<!ELEMENT clear_cache (#PCDATA)>
<!ELEMENT workspace (#PCDATA)>
<!ELEMENT cb_dir (#PCDATA)>
<!ELEMENT cb_host (#PCDATA)>
<!ELEMENT service_host (#PCDATA)>
<!ELEMENT local_replay (#PCDATA)>
<!ELEMENT ignore_header_errors (#PCDATA)>

=== LongJohnCoder/RESim/cgc-monitor/simics/monitorCore/replay_master.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE replay_master SYSTEM "/usr/share/cgc-monitoring/replay_master.dtd">
<replay_master>
  <cache>yes</cache>
  <clear_cache>yes</clear_cache>
  <workspace>/mnt/simics/simicsWorkspace</workspace>
  <cb_dir>targetStage/repo/</cb_dir>
  <cb_host>master</cb_host>
  <service_host>172.16.128.1</service_host>
  <local_replay>no</local_replay>
  <ignore_header_errors>no</ignore_header_errors>
</replay_master>
